#!/bin/sh

episode_id=$(printf "%s" "$1" | sed -nE "s_.*-([0-9]*)\.([0-9]*)\$_\2_p")

# request to get the embed
embed_link=$(curl -s "https://flixhq.to/ajax/sources/${episode_id}" | sed -nE "s_.*\"link\":\"([^\"]*)\".*_\1_p")

# get the juicy links
parse_embed=$(printf "%s" "$embed_link" | sed -nE "s_(.*)/embed-(4|6)/(.*)\?z=\$_\1\t\2\t\3_p")
provider_link=$(printf "%s" "$parse_embed" | cut -f1)
source_id=$(printf "%s" "$parse_embed" | cut -f3)
embed_type=$(printf "%s" "$parse_embed" | cut -f2)

key="$(curl -s "https://github.com/enimax-anime/key/blob/e${embed_type}/key.txt" | sed -nE "s_.*js-file-line\">(.*)<.*_\1_p")"
json_data=$(curl -s "${provider_link}/ajax/embed-${embed_type}/getSources?id=${source_id}" -H "X-Requested-With: XMLHttpRequest")

[ -z "$json_data" ] && echo "Could not get data from ${provider_link}/ajax/embed-${embed_type}/getSources?id=${source_id}" && exit 1

encrypted=$(printf "%s" "$json_data" | tr "{}" "\n" | sed -nE "s_.*\"file\":\"([^\"]*)\".*_\1_p" | grep "\.m3u8")
if [ -n "$encrypted" ]; then
	video_link=$(printf "%s" "$json_data" | tr "{|}" "\n" | sed -nE "s_.*\"file\":\"([^\"]*)\".*_\1_p" | head -1)
else
	key="$(curl -s "https://github.com/enimax-anime/key/blob/e${embed_type}/key.txt" | sed -nE "s_.*js-file-line\">(.*)<.*_\1_p")"
	encrypted_video_link=$(printf "%s" "$json_data" | tr "{|}" "\n" | sed -nE "s_.*\"sources\":\"([^\"]*)\".*_\1_p" | head -1)
      video_link=$(printf "%s" "$encrypted_video_link" | base64 -d |
		openssl enc -aes-256-cbc -d -md md5 -k "$key" 2>/dev/null | sed -nE "s_.*\"file\":\"([^\"]*)\".*_\1_p")
      json_data=$(printf "%s" "$json_data" | sed -e "s|${encrypted_video_link}|${video_link}|")
fi

printf "%s" "$json_data" | sed -nE "s_.*\"sources\":\"([^\"]*)\".*_\1_p"
