#!/bin/sh

#script for scraping gogoanime links..

#requires "openssl" dependency
base_url="https://gogohd.net"
agent="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36"

#url taken from arguments
sub_url=$(printf "%s" "$*" | cut -d'/' -f5)
[ -z "$sub_url" ] && printf "\033[1;31m[ gogoanime ] Invalid link\n" && exit 1

printf "\033[1;36m[ gogoanime ] [ $sub_url ] Downloading webpage\n"
id=$(curl -A "$agent" -s "$base_url/videos/$sub_url" | sed -nE 's/.*iframe src="(.*)" al.*/\1/p' | sed -nE 's/.*id=([^&]*).*/\1/p')

#extracting mirror site links, and scrape them after scraping this
resp="$(curl -A "$agent" -sL "${base_url}/streaming.php?id=$id" |
		sed -nE 's/.*class="container-(.*)">/\1/p ;
			s/.*class="wrapper container-(.*)">/\1/p ;
			s/.*class=".*videocontent-(.*)">/\1/p ;
			s/.*data-value="(.*)">.*/\1/p ;
			s/.*data-status="1".*data-video="(.*)">.*/\1/p')"

printf "\033[1;36m[ gogoanime ] [ $sub_url ] Fetching video url\n"
secret_key=$(printf "%s" "$resp" | sed -n '2p' | tr -d "\n" | od -A n -t x1 | tr -d " |\n")
iv=$(printf "%s" "$resp" | sed -n '3p' | tr -d "\n" | od -A n -t x1 | tr -d " |\n")
second_key=$(printf "%s" "$resp" | sed -n '4p' | tr -d "\n" | od -A n -t x1 | tr -d " |\n")
token=$(printf "%s" "$resp" | head -1 | base64 -d | openssl enc -d -aes256 -K "$secret_key" -iv "$iv" | sed -nE 's/.*&(token.*)/\1/p')
ajax=$(printf '%s' "$id" | openssl enc -e -aes256 -K "$secret_key" -iv "$iv" -a 2>/dev/null)
#fetching video links, then decrypting it using openssl
video_url=$(curl -A "$agent" -sL -H "X-Requested-With:XMLHttpRequest" "${base_url}/encrypt-ajax.php?id=${ajax}&alias=${id}&${token}" | sed -e 's/{"data":"//' -e 's/"}/\n/' -e 's/\\//g' | base64 -d 2>/dev/null | openssl enc -d -aes256 -K "$second_key" -iv "$iv" 2>/dev/null | tr -d '\\' | sed -nE 's_.*file":"([^"]*)".*source.*_\1_p')

if [ -n "$video_url" ];then
    printf "\033[1;32m Name >>\033[0m %s\n" "$sub_url"
    printf "\033[1;32m referer >>\033[0m %s\n" "$*"
    printf "\033[1;32m URL >>\033[0m %s\n" "$video_url"
    printf "\033[0m\n"
else
    printf "\033[1;31m[ gogoanime ] [ $sub_url ] Cannot fetch final url\033[0m\n\n"
fi

fb_id=$(printf "%s" "$resp" | sed -n '/fembed/p;/embedsito/p')
dood_id=$(printf "%s" "$resp" | sed -n '/dood/p')

[ -z "$fb_id" ] || $(printf "$0" | sed 's_/[^/]*$__')/fembed "$fb_id"
[ -z "$dood_id" ] || $(printf "$0" | sed 's_/[^/]*$__')/doodstream "$dood_id"
