#!/bin/sh

id=$(printf "%s" "$1" | sed -e 's/.*\/\([0-9]*\).*/\1/')
[ -z "$id" ] && id=$(curl -sI "$1" | sed -nE "s@Location: .*/video/([0-9]*).*@\1@p")
[ -z "$id" ] && echo "Could not find ID" && exit 1

curl -s "https://api-h2.tiktokv.com/aweme/v1/feed/?aweme_id=${id}" -A "uwu" |
	grep -oE '\["([^/]*)(//v[^"]*)' | head -1 | sed 's/\["//;s_\u0026_\&_g;s_\\__g'
