#!/bin/sh

STATUS_ID=$(printf "%s" "$1" | sed -e 's/.*status\/\([0-9]*\).*/\1/')
JSON_INPUT="https://api.twitter.com/1.1/statuses/show/${STATUS_ID}.json?cards_platform=Web-12&include_cards=1&include_reply_count=1&include_user_entities=0&tweet_mode=extended"

TOKEN_1="AAAAAAAAAAAAAAAAAAAAANRILgAAAAAAnNwIzUejRCOuH5E6I8xnZz4puTs%3D1Zv7ttfk8LF81IUq16cHjhLTvJu4FA33AGWWjCpTnA"
TOKEN_2="AAAAAAAAAAAAAAAAAAAAAPYXBAAAAAAACLXUNDekMxqa8h%2F40K4moUkGsoc%3DTYfbDKbT3jJPCEVnMYqilB28NHfOPqkca3qaAxGfsyKCs0wRbw"

JSON=$(curl -s "${JSON_INPUT}" \
-H "Authorization: Bearer $TOKEN_1" \
-H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.20 Safari/537.36")

VIDEO_LINK=$(printf "%s" "$JSON" | tr "{|}" "\n" | sed -nE "s@.*\"url\":\"(https:\\\/\\\/video[^\"]*)\".*@\1@p" | tr -d '\\'|head -1)

printf "%s" "$VIDEO_LINK"
