#!/bin/sh

#script for extracting youtube urls

#extracting ID from arguments
id=$(printf "$*" | cut -d"=" -f2 | cut -d"/" -f4)

#user-agent
agent="com.google.android.youtube/17.31.35 (Linux; U; Android 11) gzip"

json="{
  \"context\": {
    \"client\": {
      \"clientName\": \"ANDROID\",
      \"clientVersion\": \"17.31.35\",
      \"androidSdkVersion\": 30,
      \"userAgent\": \"$agent\",
      \"hl\": \"en\",
      \"timeZone\": \"UTC\",
      \"utcOffsetMinutes\": 0
    }
  },
  \"videoId\": \"$id\",
  \"params\": \"8AEB\",
  \"playbackContext\": {
    \"contentPlaybackContext\": {
      \"html5Preference\": \"HTML5_PREF_WANTS\"
    }
  },
  \"contentCheckOk\": true,
  \"racyCheckOk\": true
}"

#main logic
data=$(curl -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.115 Safari/537.36" -s "https://www.youtube.com/watch?v=$id&bpctr=9999999999&has_verified=1" -o /dev/null -c - | curl -X POST -A "$agent" -s "https://www.youtube.com/youtubei/v1/player?key=AIzaSyA8eiZmM1FaDVjRy-df2KTyQ_vz_yYM39w&prettyPrint=false" -H "content-type:application/json" -H "x-youtube-client-name:3" -H "x-youtube-client-version:17.31.35" -d "$json" -b - | tr "{|}" '\n' | sed -nE 's_.*title":"([^"]*)",.*_\1_p;s_.*,"url":"([^"]*)","mimeType":"(.*)","bit.*(height)?":([^,]*),.*_\4\t|\t\2\t|\t\1_p')

title=$(printf "%s" "$data" | tail -1)
urls=$(printf "%s" "$data" | sed '$d')

if [ -n "$urls" ];then
    printf "Name >> %s\n" "$title"
    printf "referer >> %s\n" "$*"
    printf "URL >>\n%s\n" "$urls"
else
    printf "Cannot fetch final urls"
fi
