#!/bin/sh

[ -z "$1" ] && echo "No URL provided" && exit 1

case "$1" in
  *tiktok*)
    extractors/tiktok "$1"
    ;;
  *instagram*)
    extractors/instagram "$1"
    ;;
  *fembed*)
    extractors/fembed "$1"
    ;;
  *dood*)
    extractors/doodstream "$1"
    ;;
  *)
    echo "Unsupported URL"
    exit 1
    ;;
esac

