#!/bin/sh

[ -z "$1" ] && echo "No URL provided" && exit 1

case "$1" in
  *tiktok*)
     $(printf "$0" | sed 's_/[^/]*$__')/extractors/tiktok "$1"
    ;;
  *instagram*)
    $(printf "$0" | sed 's_/[^/]*$__')/extractors/instagram "$1"
    ;;
  *fembed*|*embedsito*)
    $(printf "$0" | sed 's_/[^/]*$__')/extractors/fembed "$1"
    ;;
  *dood*)
    $(printf "$0" | sed 's_/[^/]*$__')/extractors/doodstream "$1"
    ;;
  *youtu*)
    $(printf "$0" | sed 's_/[^/]*$__')/extractors/youtube "$1"
    ;;
  *membed*)
    $(printf "$0" | sed 's_/[^/]*$__')/extractors/membed "$1"
    ;;
  *)
    echo "Unsupported URL"
    exit 1
    ;;
esac

