#!/bin/sh

[ -z "$1" ] && echo "No URL provided" && exit 1

case "$1" in
  *tiktok.com*)
    extractors/tiktok "$1"
    ;;
  *instagram.com*)
    extractors/instagram "$1"
    ;;
  *fembed.com*)
    extractors/fembed "$1"
    ;;
  *)
    echo "Unsupported URL"
    exit 1
    ;;
esac

